# Setup
title:               Anton's Eclectic Blog
tagline:             'We all need a space to yell into the void.'
description:         'It was either starting a blog no one would read or start a podcast nobody would listen to.'
url:                 https://antonbriganti.github.io
baseurl:             /
paginate:            5
permalink:           pretty
future:              true

# Gems
plugins:
  - jekyll-paginate

# Custom vars
repository:          antonbriganti/antonbriganti.github.io
