# Setup
title:               Anton's Eclectic Blog
tagline:             'A place for me to write about whatever'
description:         'We all need a space to yell into the void.'
url:                 https://antonbriganti.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
