# Setup
title:               Anton's Eclectic Blog
tagline:             'We all need a space to yell into the void.'
description:         'A place for me to write about whatever'
url:                 https://antonbriganti.github.io
baseurl:             /
paginate:            5
permalink:           pretty
future:              true

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
